### PR TITLE
Fix small issues to make it more rubyst

### PR DESCRIPTION
**Pull request by MalloZup**

### CODE REVIEW

**Comment by ereslibre** [comment]
Our SUSE style guide forces double quotes everywhere. We could use rubocop here, but it was meant to be a very simple script.

**Comment by MalloZup** [comment]
Ok thx Ereslibre i didnt know that. What is this  Suse style guide? It is as script or syntax checker that run somewhere? For this pr i just used rubocop

**Comment by ereslibre** [comment]
Hello @MalloZup. Yes it is here: https://github.com/SUSE/style-guides

Please note that I didn't run rubocop on it (even with SUSE style guides), so if a PR fixes the issue using our SUSE rubocop personalized cops it would be a nice addition :)

Thank you @MalloZup.

**Comment by MalloZup** [comment]
@ereslibre thx for feedback.
One question that come in my mind about this  SUSE/style-guides rubocop: why it exist something that(suse/style-guides) differ from upstream rubocop?

**Comment by MalloZup** [comment]
#4 fixed there

**Comment by ereslibre** [comment]
> One question that come in my mind about this SUSE/style-guides rubocop: why it exist something that(suse/style-guides) differ from upstream rubocop?

Sorry for not following up here. SUSE has its own ideas on how ruby should look like, and all ruby-based projects in the company should respect this rubocop guidelines (the ones specified in https://github.com/SUSE/style-guides).

While rubocop has some suggested defaults, SUSE might have different ideas in this regard. The important thing is that all ruby within the company looks alike.

Thank you again for your PR.

**Pull request closed without merging**
